### ISSUE TITLE
Exception: Interface maps for generic interfaces on arrays cannot be retrieved

### ISSUE THREAD

**Issue by ilobilo** [CosmosOS/IL2CPU#109]
I'm trying to make a shell in cosmos.
to split command and arguments this is the code i use:
`string command = Regex.Replace(input.Split()[0], @"[^0-9a-zA-Z\]+", "");`
`string[] args = input.Split(" ").Skip(1).ToArray();`
`args = args.Where(x => !String.IsNullOrWhiteSpace(x)).ToArray();`
but when i compile error shows up.

sorry for bad grammar.

**Comment by BlitzWolfMatthew** [comment]
What is your error? We need the error.

**Comment by MishaTY** [comment]
Regex is not supported in Cosmos. Try to use some thing else like string.replace

**Comment by ilobilo** [comment]
thanks
