### ISSUE TITLE
Incorrect sorting in CompilerEngine.cs

### ISSUE THREAD

**Issue by VasilievSerg** [CosmosOS/IL2CPU#143]
Hello,
Looks like the `LoadBootEntries` method performs invalid ordering.

```
private void LoadBootEntries()
{

  ....
  mBootEntries = mBootEntries.OrderBy(e => e.Value)
                             .OrderByDescending(e => e.Value.HasValue)
                             .ToDictionary(e => e.Key, e => e.Value);
  ....
}
```

Most likely, there should be the `ThenByDescending `invocation instead of `OrderByDescending`.
Here is [the link](https://github.com/CosmosOS/IL2CPU/blob/a85d287fc31d73dcc8028bb39d01a1b21f040723/source/Cosmos.IL2CPU/CompilerEngine.cs#L462).

**Comment by quajak** [comment]
Thanks, should be fixed by https://github.com/CosmosOS/IL2CPU/pull/144
