### ISSUE TITLE
Implement generic methods on arrays

### ISSUE THREAD

**Issue by jp2masa** [CosmosOS/IL2CPU#15]
_From @jp2masa on February 21, 2017 19:19_

Currently we don't handle generic methods on arrays.
Example:
```csharp
IEnumerable<string> xEnumerable;
string[] xArray = new string[] { "a", "b", "c" };
xEnumerable = xArray;
xEnumerable.GetEnumerator();
```
This code won't work, because Array doesn't have an implementation for this method. Array can be used as ICollection\<T\>, IEnumerable\<T\> and IList\<T\>
The implementations for these interfaces are in System.SZArrayHelper, but the compiler needs an implementation that replaces calls to the generic method on arrays with calls to the methods in SZArrayHelper.

_Copied from original issue: CosmosOS/Cosmos#583_

**Comment by fanoI** [comment]
We can take inspiration from what has been done in CoreRT and implement explicitely Array<T>:
https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Array.CoreRT.cs#L1428

I this the other piece that make this working seamless:
https://github.com/dotnet/corert/blob/master/src/Runtime.Base/src/System/Array.cs#L47
