### ISSUE TITLE
Improve label name

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/IL2CPU#150]
> The problem with including the entire assembly name in the label is that its too long
> so an idea could be that we create a short unique id for each assembly as we encounter it
> and append that to each label  
@quajak

Better approach for https://github.com/CosmosOS/IL2CPU/issues/122

**Comment by charlesbetros** [comment]
How about the Id from our debug database? There is an assemblies table there with each having an integer Id.

**Comment by quajak** [comment]
That could work
