### ISSUE TITLE
Exception: Interface maps for generic interfaces on arrays cannot be retrieved

### ISSUE THREAD

**Issue by Nufflee** [CosmosOS/IL2CPU#26]
Hey guys, I have a really weird issue, I have this code (https://pastebin.com/JQiqN3py) and it's giving me this exception (https://pastebin.com/TQbFKTCW ). I have also tried commenting out the code and it still had the same exception (potentially a problem with the build system?). How can I fix this?

Cheers!

**Comment by jp2masa** [comment]
This is a duplicate of #15

**Comment by charlesbetros** [comment]
In this case a plug for string split would be better and relatively simple. It worked before net core and we won't have generic interfaces on arrays for a while.

**Comment by charlesbetros** [comment]
Moving this to the main cosmos repo and rewording to specifically mention adding a plug.

**Comment by jp2masa** [comment]
The problem here is using `Skip(int)` on an array,

**Comment by charlesbetros** [comment]
Oh. My mistake. :) I thought it was on string.
