### ISSUE TITLE
System.InvalidOperationException: SqliteConnection does not support nested transactions.

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/IL2CPU#27]
Sometimes during TestRunner "routine" I get this error that make kernel fails.
This is the complete exception:

08:14:10.687024 Msg: Warning: Exists
08:14:25.043802 Msg: Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_INFO'
08:14:25.336979 Msg: Detecting fields for type 'Cosmos.Debug.Symbols.FIELD_MAPPING'
08:15:12.638903 Msg: Detecting fields for type 'Cosmos.Debug.Symbols.AssemblyFile'
08:15:12.706129 Msg: Error: Exception: System.InvalidOperationException: SqliteConnection does not support nested transactions.
08:15:12.706562 Msg: at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
08:15:12.714657 Msg: at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction()
08:15:12.717210 Msg: at Cosmos.Debug.Symbols.SqliteBulkCopy.WriteToServer(IDataReader reader) in C:\Users\fano\Documents\GitHub\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\SqliteBulkCopy.cs:line 36
08:15:12.737130 Msg: at Cosmos.Debug.Symbols.DebugInfo.BulkInsertT in C:\Users\fano\Documents\GitHub\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs:line 520
08:15:12.753046 Msg: at Cosmos.Debug.Symbols.DebugInfo.AddAssemblies(List`1 aAssemblies, Boolean aFlush) in C:\Users\fano\Documents\GitHub\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs:line 395
08:15:12.759681 Msg: at Cosmos.Debug.Symbols.DebugInfo.Dispose() in C:\Users\fano\Documents\GitHub\Cosmos\IL2CPU\source\IL2CPU.Debug.Symbols\DebugInfo.cs:line 545
08:15:12.797378 Msg: at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\fano\Documents\GitHub\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 246
08:15:12.846716 Error: Error invoking 'dotnet'.

**Comment by jp2masa** [comment]
This has probably been fixed by updating `Microsoft.Data.Sqlite` to version 2.0.0.
