### ISSUE TITLE
Interface maps for generic interfaces on arrays cannot be retrieved.

### ISSUE THREAD

**Issue by valentinbreiz** [CosmosOS/IL2CPU#55]
When I try to use this code `return new List<uint>(H);` inside a ` List<uint>`  function I have this error:

1>IL2CPU : error : Exception: System.ArgumentException: Interface maps for generic interfaces on arrays cannot be retrieved.
1>   at System.RuntimeType.GetInterfaceMap(Type ifaceType)
1>Message: C:\Users\valentinbreiz\Documents\GitHub\Aura-Operating-System\Aura Operating System\Aura OS\bin\Debug\netstandard2.0\Aura_OS.dll
1>Message: C:\Users\valentinbreiz\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Asm.dll
1>Message: C:\Users\valentinbreiz\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Core_Plugs.dll
1>Message: C:\Users\valentinbreiz\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.Debug.Kernel.Plugs.Asm.dll
1>Message: C:\Users\valentinbreiz\AppData\Roaming\Cosmos User Kit\Kernel\Cosmos.System2_Plugs.dll
1>   at Cosmos.IL2CPU.ILScanner.ScanMethod(MethodBase aMethod, Boolean aIsPlug, String sourceItem) in C:\Users\valentinbreiz\Documents\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 561
1>   at Cosmos.IL2CPU.ILScanner.ScanQueue() in C:\Users\valentinbreiz\Documents\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 775
1>   at Cosmos.IL2CPU.ILScanner.Execute(MethodBase aStartMethod) in C:\Users\valentinbreiz\Documents\Cosmos\IL2CPU\source\Cosmos.IL2CPU\ILScanner.cs:line 253
1>   at Cosmos.IL2CPU.CompilerEngine.Execute() in C:\Users\valentinbreiz\Documents\Cosmos\IL2CPU\source\Cosmos.IL2CPU\CompilerEngine.cs:line 168

**Comment by jp2masa** [comment]
`H` is an array?

**Comment by valentinbreiz** [comment]
Yes.

**Comment by jp2masa** [comment]
Then this is a duplicate of #15.

**Comment by valentinbreiz** [comment]
Oh sorry.
