### ISSUE TITLE
Is it possible to use IL2CPU to compile dotnet programs to regular Win32 programs for example ?

### ISSUE THREAD

**Issue by beppe9000** [CosmosOS/IL2CPU#76]

**Comment by zarlo** [comment]
yes but  you would need to mod IL2CPU

**Comment by beppe9000** [comment]
Could you give some pointers as to what needs to be modified and where to find it?
I'm not very familiar with the project, but could try to help implement that when I can.

**Comment by sgf** [comment]
maybe this is a good idea.
