### ISSUE TITLE
System.Console.OpenStandard <input | output | error> throws empty error.

### ISSUE THREAD

**Issue by danbulant** [CosmosOS/IL2CPU#86]

**Comment by danbulant** [comment]
Here are more things that throw empty exception if used:
* System.Console.OpenStandardInput
* System.Console.OpenStandardOutput
* System.Console.OpenStandardError
* Exception.StackTrace (looks like only .toString() can be used, which doesn't give enough information)

**Comment by charlesbetros** [comment]
This is caused by missing plugs. Those would be added to the Cosmos kernel rather than the IL2CPU repository.
